# Generated by Django 5.2.6 on 2025-09-24 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users')),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('email', models.CharField()),
                ('country', models.CharField(max_length=200)),
                ('house_name', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('username', models.CharField()),
                ('password', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catogory', models.IntegerField()),
                ('image', models.ImageField(upload_to='products')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('org_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users')),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('email', models.CharField()),
                ('country', models.CharField(max_length=200)),
                ('house_name', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('licens', models.CharField(blank=True, max_length=200, null=True)),
                ('gst', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField()),
                ('password', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('review_img', models.ImageField(blank=True, null=True, upload_to='products')),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.costumer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.seller'),
        ),
    ]
