# Generated by Django 5.2.6 on 2025-09-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_gst_seller_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='costumer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.DeleteModel(
            name='Costumer',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
