# Generated by Django 5.2.6 on 2025-09-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='item',
            field=models.ManyToManyField(to='home.product'),
        ),
    ]
