# Generated by Django 5.2.6 on 2025-09-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_item_item_item_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
