# Generated by Django 5.2.6 on 2025-09-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_product_seller_remove_review_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='costumer',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='Costumer',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
