# Generated by Django 5.2.6 on 2025-10-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_order_seller_orders_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='seller',
        ),
    ]
