# Generated by Django 5.2.6 on 2025-10-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_orders_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='n',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, null=True),
        ),
    ]
