# Generated by Django 5.2.6 on 2025-10-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_order_n_remove_orders_status_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='n',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=100, null=True),
        ),
    ]
