# Generated by Django 5.2.6 on 2025-10-18 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_order_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='costumer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='n',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='costumer',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='n',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_date',
        ),
    ]
