# Generated by Django 5.2.6 on 2025-10-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_order_amount_remove_order_costumer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
