# Generated by Django 5.2.6 on 2025-10-18 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_delete_order_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, null=True)),
                ('n', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=100, null=True)),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.costumer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True)),
                ('n', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=100, null=True)),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.costumer')),
            ],
        ),
    ]
