# Generated by Django 5.2.6 on 2025-10-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_order_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
