# Generated by Django 5.2.6 on 2025-10-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_product_image1_product_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
