# Generated by Django 5.2.6 on 2025-10-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
